### PR TITLE
MI-196: ubuntu changed the syntax for esm registration command

### PR DESCRIPTION
**Pull request by lbjay**
This change modifies the recipe to use the updated ubuntu advantage
agent syntax for enabling ESM. There is also now a single `token`
value that must be configured in the cluster config.

### CODE REVIEW

**Review by karendolan — COMMENTED** [review]
The pull looks Ok to me, has it been tested on a dev cluster?

**Comment by lbjay** [comment]
Tested on staging.

**Review by rute-santos — APPROVED** [review]

**Review by karendolan — APPROVED** [review]
Looks good to me

**Comment by lbjay** [comment]
These changes were merged, although the PR got confused by a conflict in the changelog (which i could swear i resolved).

**Pull request closed without merging**
